### ISSUE TITLE
Tacoz TCZ Price is not displayed correctly

### ISSUE THREAD

**Issue by josim** [jmagly/build.teztools.io#4]
The Tacoz TCZ price does not show up correctly, due to that the estimated value on "your inventory" page is incorrect.

Contract Address: KT1GGxCNiJ7yaBAH4hAw5AHXbP3PSmAiy3wK

<img width="172" alt="tacos_teztools" src="https://user-images.githubusercontent.com/6659705/118479399-43844100-b711-11eb-834c-692a00be4687.png"> <img width="446" alt="tacos_quipi" src="https://user-images.githubusercontent.com/6659705/118479413-467f3180-b711-11eb-8ddd-ea16b9d67842.png">

**Comment by jmagly** [comment]
special snowflake just like some of the bender coins, have to write code just for their prices!

**Comment by jmagly** [comment]
Ok got it sorted, re-worked the math a bit and got much better precision with more of the tokens. though a couple need more massaging TCZ should be fine now!
